### PR TITLE
add STAC, IIT Mandi logo to header

### LINKED ISSUE #6: Banner Design
This one is for you @akshat157 
cc @abhijeetmanhas 
Banner can be like:
- Left Side center Large AstraX logo.
- Right Side - 2 Buttons (Later in PR, we will decide what they should do)
- Clear Mention of dates
- Logos of STAC and IIT Mandi (Wil work even if small)

Mobile View is upto you.

### PR DESCRIPTION
**Pull request by akshat157**
Fixes #6 
Previews
screenshot from 2019-01-18 06-28-04
screenshot from 2019-01-18 06-27-38

Suggestions - Please fix the responsiveness and image widths on mobile displays.
Hope this will do.

### CODE REVIEW

**Comment by shreyasbapat** [comment]
@akshat157 The logo of IIT Mandi and STAC in desktop version look out of symmetry, also, the logo of IIT Mandi should be colored.

And you didn't address this: 

> Right Side - 2 Buttons (Later in PR, we will decide what they should do)

Can you invest 30 more minutes of your life to fix these?

> Please fix the responsiveness and image widths on mobile displays.

As I am not free neither proficient in doing so. Also, the webpage is deployed already and people are looking at it. So, we can't break anything

**Comment by shreyasbapat** [comment]
@akashdakoor  Please give him the AstraX logo.

**Comment by akshat157** [comment]
I'll be out of station for a while but I'll look into it.🙂

**Comment by shreyasbapat** [comment]
> Mandi should be colored.
should not be .

**Pull request closed without merging**
